# Need to add allowHostDirVolumePlugin, allowPrivilegedContainer
# check unAsUser value

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: nonroot
  annotations:
    policies.kyverno.io/description: >-
      nonroot Policy - Allow nonroot privilege.      
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: scc-nonroot-bad-pod
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          This is nonroot policy  - provide access at host level.
        pattern:
          spec:
            securityContext:
              supplementalGroups: "?*"
            =(hostNetwork): false
            =(hostIPC): false
            =(hostPID): false 
            =(ephemeralContainers):
                securityContext:
                  allowPrivilegeEscalation: true
                  runAsNonRoot: "true"
                  readOnlyRootFilesystem: false
                  seLinuxOptions:
                    level: "?*"
            =(initContainers):
                securityContext:
                  allowPrivilegeEscalation: true
                  runAsNonRoot: "true"
                  readOnlyRootFilesystem: false
                  seLinuxOptions:
                    level: "?*"
            containers:
            - securityContext:
                allowPrivilegeEscalation: true
                runAsNonRoot: "true"
                readOnlyRootFilesystem: false
                seLinuxOptions:
                  level: "?*"
    - name: restricted-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: NotEquals
          value: DELETE
      validate:
        message: >-
          Only the following types of volumes may be used: configMap, downwardAPI,
          emptyDir, persistentVolumeClaim, projected, and secret.
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.volumes[].keys(@)[] || '' }}"
              operator: AnyNotIn
              value:
              - name
              - configMap
              - downwardAPI
              - emptyDir
              - hostPath
              - persistentVolumeClaim
              - projected
              - secret
              - ''
    - name: host-ports-none
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Use of host ports is disallowed. The fields spec.containers[*].ports[*].hostPort
          , spec.initContainers[*].ports[*].hostPort, and spec.ephemeralContainers[*].ports[*].hostPort
          must either be unset or set to `0`.          
        pattern:
          spec:
            =(ephemeralContainers):
              - =(ports):
                  - =(hostPort): 0
            =(initContainers):
              - =(ports):
                  - =(hostPort): 0
            containers:
              - =(ports):
                  - =(hostPort): 0
    - name: required-drop-capabilities
      match:
        any:
        - resources:
            kinds:
              - Pod
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: NotEquals
          value: DELETE
      validate:
        message: >-
                    Any container needs to have KILL, MKNOD, SETUID, SETGID capabilities.
        foreach:
          - list: request.object.spec.[ephemeralContainers, initContainers, containers][]
            deny:
              conditions:
                any:
                - key: KILL
                  operator: AnyNotIn
                  value: "{{ element.securityContext.capabilities.drop[].to_upper(@) || `[]` }}"
                - key: MKNOD
                  operator: AnyNotIn
                  value: "{{ element.securityContext.capabilities.drop[].to_upper(@) || `[]` }}"
                - key: SETUID
                  operator: AnyNotIn
                  value: "{{ element.securityContext.capabilities.drop[].to_upper(@) || `[]` }}"
                - key: SETGID
                  operator: AnyNotIn
                  value: "{{ element.securityContext.capabilities.drop[].to_upper(@) || `[]` }}"

