apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: calico-node
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Visa-Custom
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.9.2
    kyverno.io/kubernetes-version: "1.22-1.26"
    policies.kyverno.io/description: >-
      The security settings and restrictions for the calico node pods.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: securityContext-hostlevelvalidation
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Policy for calico node.
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
              fsGroup: '1-65535'
              supplementalGroups: '1-65535'
            hostNetwork: "true" 
            =(ephemeralContainers):
            - securityContext:
                privileged: true
                allowPrivilegeEscalation: true
                capabilities:
                  drop:
                    - all
                seLinuxOptions:
                  level: "?*"
              =(ports): 
               - =(hostPort): '?*'
            =(initContainers):
            - securityContext:
                privileged: true
                allowPrivilegeEscalation: true
                capabilities:
                  drop:
                    - all
                seLinuxOptions:
                  level: "?*"
              =(ports): 
               - =(hostPort): '?*'
            containers:
            - securityContext:
                privileged: true
                allowPrivilegeEscalation: true
                capabilities:
                  drop:
                    - all
                seLinuxOptions:
                  level: "?*"
              =(ports): 
               - =(hostPort): '?*'
    - name: restricted-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Only the following types of volumes may be used: hostPath,configMap,downwardAPI,
          emptyDir,persistentVolumeClaim,projected and secret.          
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.volumes[].keys(@)[] || '' }}"
              operator: AnyNotIn
              value:
              - hostPath
              - configMap
              - downwardAPI
              - emptyDir
              - persistentVolumeClaim
              - projected
              - secret
              - ''
