apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kube-state-metrics-operator-policy
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.9.2
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Kube-State-Metrics operator Security Context settings      
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: securityContext-hostlevelvalidation
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Policy for TSB controle-plane.         
        pattern:
          spec:
            securityContext:
              fsGroup: '1-65535'
              supplementalGroups: '1-65535'
            =(ephemeralContainers):
              securityContext:
                allowPrivilegeEscalation: "true"
                seLinuxOptions:
                  level: "?*"
            =(initContainers):
              securityContext:
                allowPrivilegeEscalation: "true"
                seLinuxOptions:
                  level: "?*"
            containers:
              - securityContext:
                 allowPrivilegeEscalation: "true"
                 seLinuxOptions:
                   level: "?*"
    - name: restricted-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          kube-state-metrics is allowed only volume type secret         
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.volumes[].keys(@)[] || '' }}"
              operator: AnyNotIn
              value:
              - secret
              - ''
