apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: anyuid-policy
  annotations:
    policies.kyverno.io/title: restricted with anyuid
    policies.kyverno.io/category: Visa-Custom 
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.9.2
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      This policy enforces pod security standards that mimic 
      the behavior of the Restricted PodSecurityPolicy (PSP) while allowing 
      users to run pods with any UID and any GID.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: securityContext-hostlevelvalidation
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          anyuid provides all features of the restricted SCC but allows users to run with any UID and any GID.         
        pattern:
          spec:
            securityContext:
            =(hostNetwork): "false"
            =(hostPID): "false"
            =(hostIPC): "?*"
            =(ephemeralContainers):
              securityContext:
                allowPrivilegeEscalation: "false"
                privileged: "false"
                capabilities:
                  drop:
                    - MKNOD
                readOnlyRootFilesystem: "true"
                seLinuxOptions:
                  type: "MustRunAs"
            =(initContainers):
              securityContext:
                allowPrivilegeEscalation: "false"
                privileged: "false"
                capabilities:
                  drop:
                    - MKNOD
                readOnlyRootFilesystem: "true"
                seLinuxOptions:
                  level: "MustRunAs"
            containers:
              - securityContext:
                 allowPrivilegeEscalation: "false"
                 privileged: "false"
                 capabilities:
                   drop:
                    - MKNOD
                 readOnlyRootFilesystem: "true"
                 seLinuxOptions:
                   level: "MustRunAs"
    - name: restricted-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Only the following types of volumes may be used: configMap, downwardAPI,
          emptyDir, persistentVolumeClaim, projected, and secret.          
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.volumes[].keys(@)[] || '' }}"
              operator: AnyNotIn
              value:
              - configMap
              - downwardAPI
              - emptyDir
              - persistentVolumeClaim
              - projected
              - secret

