apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodSecurityPolicy","metadata":{"annotations":{"seccomp.security.alpha.kubernetes.io/allowedProfileNames":"*","seccomp.security.alpha.kubernetes.io/defaultProfileName":"docker/default"},"name":"unprivileged"},"spec":{"allowPrivilegeEscalation":false,"allowedCapabilities":[],"allowedHostPaths":[{"pathPrefix":"/dev/null","readOnly":true}],"fsGroup":{"rule":"RunAsAny"},"hostIPC":false,"hostNetwork":false,"hostPID":false,"hostPorts":[{"max":65535,"min":0}],"privileged":false,"runAsUser":{"rule":"RunAsAny"},"seLinux":{"rule":"RunAsAny"},"supplementalGroups":{"rule":"RunAsAny"},"volumes":["*"]}}
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
  creationTimestamp: "2022-09-24T23:35:56Z"
  managedFields:
  - apiVersion: policy/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:seccomp.security.alpha.kubernetes.io/allowedProfileNames: {}
          f:seccomp.security.alpha.kubernetes.io/defaultProfileName: {}
      f:spec:
        f:allowPrivilegeEscalation: {}
        f:allowedHostPaths: {}
        f:fsGroup:
          f:rule: {}
        f:hostPorts: {}
        f:runAsUser:
          f:rule: {}
        f:seLinux:
          f:rule: {}
        f:supplementalGroups:
          f:rule: {}
        f:volumes: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-09-24T23:35:56Z"
  name: unprivileged
  resourceVersion: "359"
  uid: 72411631-11d0-4a96-aba1-4aa7368ef01c
spec:
  allowPrivilegeEscalation: false
  allowedHostPaths:
  - pathPrefix: /dev/null
    readOnly: true
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - max: 65535
    min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
