apiVersion: v1
kind: Pod
metadata:
  name: scc-anyuid-ba-pod
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  volumes:
  - name: config-vol
    hostPath: 
      path: /home/openapianil/samplePV
      type: Directory
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    ports:
    - hostPort: 900
      containerPort: 900
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      privileged: true
      capabilities:
        drop:
          - all
