apiVersion: v1
kind: Pod
metadata:
  name: visa-restriced-rw-badpod
spec:
  serviceAccountName: badpod
  hostNetwork: true
  hostPID: true 
  hostIPC: true
  securityContext:
    runAsUser: 1000
    fsGroup: 1001
    runAsNonRoot: true
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    hostPath: 
      path: /dev
      type: Directory
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /dev
      readOnly: false
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: false
      privileged: true
      capabilities:
        drop:
          - KILL
          - MKNOD
          - SYS_CHROOT
          - SETUID
          - SETGID
      seLinuxOptions:
        level: "s0:c123,c456"
