apiVersion: v1
kind: Pod
metadata:
  name:  good-pod-unprivileged
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    hostPath:
      path: /dev/null
      type: Directory
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    ports:
    - hostPort: 65535
    volumeMounts:
    - name: config-vol
      mountPath: /var/test
      readOnly: true
    securityContext:
      allowPrivilegeEscalation: false
      seLinuxOptions:
        level: "s0:c123,c456"
