apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: unprivileged
  annotations:
    policies.kyverno.io/title: unprivileged
    policies.kyverno.io/category: Visa-Custom
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.9.2
    kyverno.io/kubernetes-version: "1.23-1.26"
    policies.kyverno.io/description: >-
      Custom Policy for unprivileged access deployment at Visa
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: securityContext-hostlevelvalidation
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Policy for unprivileged Access.        
        pattern:
          spec:            
            securityContext:
              runAsUser: "*"
              fsGroup: "*"
              supplementalGroups: "*"  
            =(ephemeralContainers):          
              securityContext:
                allowPrivilegeEscalation: false
                seLinuxOptions:
                  level: "?*"
            =(initContainers):          
              securityContext:
                allowPrivilegeEscalation: false
                seLinuxOptions:
                  level: "?*"
            containers:          
            - securityContext:
                allowPrivilegeEscalation: false
                seLinuxOptions:
                  level: "?*"         
    - name: host-ports-restriction
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Use of host ports is disallowed. The fields spec.containers[*].ports[*].hostPort
          , spec.initContainers[*].ports[*].hostPort, and spec.ephemeralContainers[*].ports[*].hostPort
          must either be unset or set between `0-65535`.          
        pattern:
          spec:
            =(ephemeralContainers):
              - =(ports):
                  - =(hostPort): "0-65535"
            =(initContainers):
              - =(ports):
                  - =(hostPort): "0-65535"
            containers:
              - =(ports):
                  - =(hostPort): "0-65535"    
    - name: limit-hostpath-to-slash-dev-slash-null
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.volumes[?hostPath] | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
        - key: "{{request.operation || 'BACKGROUND'}}"
          operator: AnyIn
          value:
          - CREATE
          - UPDATE
      validate:
        message: hostPath volumes are confined to /dev/null.
        foreach:
        - list: "request.object.spec.volumes[?hostPath].hostPath"
          deny:
            conditions:
              any:
              - key: "{{ element.path  | to_string(@)  }}"
                operator: NotEquals
                value: "/dev/null"
   
   
   
   

