apiVersion: v1
kind: Pod
metadata:
  name: calico-kube-controllers-good-pod
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    secret:
      secretName: test
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /dev/null
    ports: 
    - name: test
      hostPort: 80
      containerPort: 80
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
      seLinuxOptions:
        level: "s0:c123,c456"
