apiVersion: v1
kind: Pod
metadata:
  name: calico-kube-controllers-bad-pod
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    hostPath:
      path: /dev/test
      type: DirectoryOrCreate
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
    ports: 
    - name: test
      hostPort: 80
      containerPort: 80
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
      capabilities:
        drop:
          - all
      seLinuxOptions:
        level: "s0:c123,c456"
