apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: calico-kube-controllers
  annotations:
    policies.kyverno.io/title: calico-kube-controllers
    policies.kyverno.io/category: Visa-Custom
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.9.2
    kyverno.io/kubernetes-version: "1.23-1.26"
    policies.kyverno.io/description: >-
      Custom Policy for calico-kube-controllers deployment at Visa
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: securityContext-hostlevelvalidation
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - kyverno
              - nirmata-system
      validate:
        message: >-
          Policy for calico-kube-controllers.        
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
              fsGroup: '1-65535'
              supplementalGroups: '1-65535'   
            =(ephemeralContainers):          
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - all
                seLinuxOptions:
                  level: "?*"
            =(initContainers):          
              securityContext:
                allowPrivilegeEscalation: false
                privileged: false
                capabilities:
                  drop:
                    - all
                seLinuxOptions:
                  level: "?*"
            containers:          
            - securityContext:
                allowPrivilegeEscalation: false
                privileged: false
                seLinuxOptions:
                  level: "?*"
                capabilities:
                  drop:
                    - all             
    - name: restricted-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - kyverno
              - nirmata-system
      validate:
        message: >-
          Only the following types of volumes may be used: configMap, downwardAPI,
          emptyDir, persistentVolumeClaim, projected, and secret.          
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.volumes[].keys(@)[] || '' }}"
              operator: AnyNotIn
              value:
              - configMap
              - downwardAPI
              - emptyDir
              - persistentVolumeClaim
              - projected
              - secret
              - ''
    - name: host-ports-restriction
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - kyverno
              - nirmata-system
      validate:
        message: >-
          Use of host ports is disallowed. The fields spec.containers[*].ports[*].hostPort
          , spec.initContainers[*].ports[*].hostPort, and spec.ephemeralContainers[*].ports[*].hostPort
          must either be unset or set between `0-65535`.          
        pattern:
          spec:
            =(ephemeralContainers):
              - =(ports):
                  - =(hostPort): "0-65535"
            =(initContainers):
              - =(ports):
                  - =(hostPort): "0-65535"
            containers:
              - =(ports):
                  - =(hostPort): "0-65535"