apiVersion: v1
kind: Pod
metadata:
  name: scc-anyuid-good-pod
spec:
  hostNetwork: false
  hostPID: false
  hostIPC: false
  volumes:
  - name: config-vol
    emptyDir: {}
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: false
      privileged: false
      capabilities:
        drop:
          - all
      seLinuxOptions:
        level: "s0:c123,c456"
