apiVersion: v1
kind: Pod
metadata:
  name: good-pod
spec:
  hostNetwork: false
  hostPID: false 
  hostIPC: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    hostPath:
      path: /
      type: DirectoryOrCreate
  - name: dev-run
    hostPath:
      path: /var/run
      type: DirectoryOrCreate
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /
    - name: dev-run
      mountPath: /var/run
    ports: 
    - name: test
      hostPort: 80
      containerPort: 80
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      privileged: false
      capabilities:
        drop:
          - all
      seLinuxOptions:
        level: "s0:c123,c456"