apiVersion: v1
kind: Pod
metadata:
  name: restricted-good-pod
spec:
  hostNetwork: true
  hostPID: true 
  hostIPC: true
  securityContext:
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    emptyDir: {}
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
    ports: 
    - name: test
      hostPort: 80
      containerPort: 80
    securityContext:
      allowPrivilegeEscalation: "true"
      privileged: "true"
      capabilities:
        drop:
          - all
      seLinuxOptions:
        level: "s0:c123,c456"
