apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: boxexport-prometheus-blackbox-exporter
  annotations:
    policies.kyverno.io/title: boxexport-prometheus-blackbox-exporter
    policies.kyverno.io/category: Visa-Custom
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.10.3
    kyverno.io/kubernetes-version: "1.23-1.26"
    policies.kyverno.io/description: >-
      boxexport-prometheus-blackbox-exporter visa policy
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: securityContext-podlevelvalidation
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Policy for boxexport-prometheus-blackbox-exporter.        
        anyPattern:
      # spec.securityContext.runAsNonRoot must be set to true. If containers and/or initContainers exist which declare a securityContext field, those must have runAsNonRoot also set to true.
        - spec:
            securityContext:              
              fsGroup: '1-65535'		  
              supplementalGroups: '1-65535'
              runAsUser: '*'		   
            containers:
            - =(securityContext):
                =(allowPrivilegeEscalation): "false"
                =(runAsUser): '*'	
                =(readOnlyRootFilesystem): "true"
                =(seLinuxOptions):
                  level: "?*"	
            =(initContainers):
            - =(securityContext):
                =(allowPrivilegeEscalation): "false"
                =(runAsUser): '*'	
                =(readOnlyRootFilesystem): "true"
                =(seLinuxOptions):
                  level: "?*"	
            =(ephemeralContainers):
            - =(securityContext):
                =(allowPrivilegeEscalation): "false"
                =(runAsUser): '*'	
                =(readOnlyRootFilesystem): "true"
                =(seLinuxOptions):
                  level: "?*"							
      # All containers and initContainers must define (not optional) runAsNonRoot=true.
        - spec:
            containers:
            - securityContext:
                =(allowPrivilegeEscalation): "false"
                =(runAsUser): '*'	
                =(readOnlyRootFilesystem): "true"
                seLinuxOptions:
                  level: "?*"		
            =(initContainers):
            - =(securityContext):
                =(allowPrivilegeEscalation): "false"
                =(runAsUser): '*'	
                =(readOnlyRootFilesystem): "true"
                =(seLinuxOptions):
                  level: "?*"			
            =(ephemeralContainers):
            - =(securityContext):
                =(allowPrivilegeEscalation): "false"
                =(runAsUser): '*'	
                =(readOnlyRootFilesystem): "true"
                =(seLinuxOptions):
                  level: "?*"				
    - name: restricted-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Only the following types of volumes may be used: configMap and secret.          
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.volumes[].keys(@)[] || '' }}"
              operator: AnyNotIn
              value:
              - name
              - configMap
              - secret
              - ''               