apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-hostnetwork-v2
spec:
  hostNetwork: false
  hostPID: false
  hostIPC: false
  securityContext:
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    hostPath:
      path: /var/lib/docker/volumes/*certs
      type: Directory
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    ports:
    - hostPort: 65555
    volumeMounts:
    - name: config-vol
      mountPath: /var/lib/docker/volumes/*certs
      readOnly: true
    securityContext:
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: true
      privileged: false
      seccompProfile:
        type: Localhost
      capabilities:
        drop:
          - MKNOD
          - SETUID
          - SETGID
          - SYS_CHROOT
        add:
          - KILL
      seLinuxOptions:
        level: "s0:c123,c456"
