apiVersion: v1
kind: Pod
metadata:
  name: good-pod-hostnetwork-v2
spec:
  hostNetwork: true
  hostPID: false
  hostIPC: false
  securityContext:
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
    - name: config-volume
      configMap:
        name: my-config-map
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    ports:
    - hostPort: 65522
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      privileged: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - all
        add:
          - NET_BIND_SERVICE
      seLinuxOptions:
        level: "s0:c123,c456"
