apiVersion: v1
kind: Pod
metadata:
  name: visa-anyuid-goodpod
spec:
  hostNetwork: false
  hostPID: false 
  hostIPC: true
  securityContext:
    runAsUser: 1000
    fsGroup: 1001
    runAsNonRoot: true
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    hostPath: 
      path: /var
      type: Directory
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /var
      readOnly: true
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      privileged: false
      capabilities:
        drop:
          - KILL
          - MKNOD
          - SYS_CHROOT
          - SETUID
          - SETGID
          - NET_RAW 
      seLinuxOptions:
        level: "s0:c123,c456"