---
apiVersion: v1
data:
  name: hello
kind: ConfigMap
metadata:
  name: my-config-map
---
apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-tsb-control-plane
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  securityContext:
    runAsUser: 1500
    fsGroup: 1500
    supplementalGroups: [2002]
  volumes:
    - name: host-volume
      hostPath:
        path: /var/mydata 
        type: Directory
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    ports:
    - hostPort: 9090
      containerPort: 9090
    volumeMounts:
    - name: host-volume
      mountPath: /tmp
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      privileged: false
      capabilities:
        drop:
          - all
      seLinuxOptions:
        level: "s0:c123,c456"
