apiVersion: v1
kind: Pod
metadata:
  name: nonroot-v2-badpod
spec:
  hostNetwork: false
  hostPID: false
  hostIPC: false
  securityContext:
    runAsUser: 1001
    runAsGroup: 3001
    fsGroup: 2001
    supplementalGroups: [4001]
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - name: config-vol
    hostPath:
      path: /dev/null
      type: DirectoryOrCreate
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      privileged: false
      capabilities:
        add:
          - all
      seLinuxOptions:
        level: "s0:c123,c456"
