apiVersion: v1
kind: Pod
metadata:
  name:  visa-anyuid-hostaccess-good-pod
spec:
  hostNetwork: false
  hostPID: false
  hostIPC: false
  securityContext:
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
  - name: configMap
    configMap:
      name: test123
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: configMap
      mountPath: /run
      readOnly: true
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      privileged: false
      capabilities:
        drop:
          - KILL
          - MKNOD
          - SYS_CHROOT
          - SETUID
          - SETGID
          - NET_RAW 
      seLinuxOptions:
        level: "s0:c123,c456"