apiVersion: v1
kind: Pod
metadata:
  name: nonroot-goodpod
spec:
  hostNetwork: false
  hostPID: false
  hostIPC: false
  securityContext:
    runAsUser: 1001
    runAsGroup: 3001
    fsGroup: 2001
    supplementalGroups: [4001]
    runAsNonRoot: true
  volumes:
  - name: config-vol
    emptyDir: {}
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: false
      privileged: false
      capabilities:
        drop:
          - KILL
          - MKNOD
          - SETUID
          - SETGID
      seLinuxOptions:
        level: "s0:c123,c456"
