apiVersion: v1
kind: Pod
metadata:
  name:  bad-pod-tekton-pipelines
spec:
  securityContext:
    runAsNonRoot: false
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    hostPath:
      path: /var/lib/docker/volumes/*certs
      type: Directory
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /var/lib/docker/volumes/*certs
      readOnly: true
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: true
      seLinuxOptions:
        level: "s0:c123,c456"
