apiVersion: v1
kind: Pod
metadata:
  name:  good-pod-tekton-pipelines
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
    - name: config-volume
      configMap:
        name: my-config-map
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seLinuxOptions:
        level: "s0:c123,c456"
