apiVersion: v1
kind: Pod
metadata:
  name: scc-kyverno-hostmount-anyuid-badpod
spec:
  hostNetwork: false
  hostPID: false
  hostIPC: false
  securityContext:
    runAsNonRoot: false
  volumes:
  - hostPath:
      path: /dev/null
      type: DirectoryOrCreate
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    ports:
    - hostPort: 80
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - all
      seLinuxOptions:
        level: "s0:c123,c456"
