apiVersion: v1
kind: Pod
metadata:
  name: cert-exporter-badpod
spec:
  hostNetwork: true
  hostPID: true 
  hostIPC: true
  securityContext:
    runAsUser: 1000
    fsGroup: 1001
    runAsNonRoot: false
    supplementalGroups: [2002]
  volumes:
  - name: config-vol
    hostPath: 
      path: /var/lib/docker/volumes/test
      type: Directory
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config-vol
      mountPath: /var/lib/docker/volumes/test
      readOnly: false
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: false
      privileged: true
      capabilities:
        drop:
          - KILL
          - MKNOD
          - SYS_CHROOT
          - SETUID
          - SETGID
          # - NET_RAW 
      seLinuxOptions:
        level: "s0:c123,c456"
