apiVersion: v1
kind: Pod
metadata:
  name:  bad-pod
spec:
  securityContext:
    runAsUser: 0
    fsGroup: 1001
    supplementalGroups: [2002]
  volumes:
  - name: secret-volume
    emptyDir: {}
  containers:
  - name: container01
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: true
      privileged: false
      seLinuxOptions:
        level: "s0:c123,c456"
