apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kube-state-metrics-operator-policy
  annotations:
    policies.kyverno.io/title: kube-state-metrics-operator-policy
    policies.kyverno.io/category: Pod Security Standards 
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.9.2
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Kube-State-Metrics operator Security Context settings      
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: securityContext-hostlevelvalidation
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Policy for TSB controle-plane.         
        anyPattern:
      # spec.securityContext.runAsNonRoot must be set to true. If containers and/or initContainers exist which declare a securityContext field, those must have runAsNonRoot also set to true.
        - spec:
            securityContext:              
              fsGroup: '1-65535'			  
              supplementalGroups: '1-65535'
              =(runAsUser): '1-65535' 			   
            containers:
            - =(securityContext):
                =(allowPrivilegeEscalation): "true|false"
                =(runAsUser): '1-65535'		
                =(seLinuxOptions):
                  level: "?*"
            =(initContainers):
            - =(securityContext):
                =(allowPrivilegeEscalation): "true|false"
                =(runAsUser): '1-65535'		
                =(seLinuxOptions):
                  level: "?*"
            =(ephemeralContainers):
            - =(securityContext):
                =(allowPrivilegeEscalation): "true|false"
                =(runAsUser): '1-65535'		
                =(seLinuxOptions):
                  level: "?*"				
      # All containers and initContainers must define (not optional) runAsNonRoot=true.
        - spec:
            containers:
            - securityContext:                
                =(runAsUser): '1-65535'
                =(allowPrivilegeEscalation): "true|false"
                =(seLinuxOptions):
                  level: "?*"
            =(initContainers):
            - =(securityContext):
                =(allowPrivilegeEscalation): "true|false"
                =(runAsUser): '1-65535'		
                =(seLinuxOptions):
                  level: "?*"
            =(ephemeralContainers):
            - =(securityContext):
                =(allowPrivilegeEscalation): "true|false"
                =(runAsUser): '1-65535'		
                =(seLinuxOptions):
                  level: "?*"			
    - name: restricted-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          kube-state-metrics is allowed only volume type secret         
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.volumes[].keys(@)[] || '' }}"
              operator: AnyNotIn
              value:
              - name
              - secret
              - ''
